[package]
name = "piggy-bank"
version = "0.0.0"
authors = ["Etienne Wallet"]
edition = "2021"
publish = false

[lib]
path = "src/lib.rs"
[dependencies.multiversx-sc]
version = "0.64.1"

[dev-dependencies]
num-bigint = "0.4.2"

[dev-dependencies.multiversx-sc-scenario]
version = "0.64.1"
