[package]
name = "esdt-minter-meta"
version = "0.0.0"
edition = "2021"
publish = false
authors = ["Etienne Wallet"]
[dependencies.esdt-minter]
path = ".."

[dependencies.multiversx-sc-meta-lib]
version = "0.64.1"
