[package]
name = "trader-sc-meta"
version = "0.0.0"
edition = "2021"
publish = false

[dependencies.trader-sc]
path = ".."

[dependencies.multiversx-sc-meta-lib]
version = "0.64.1"
default-features = false
