[package]
name = "piggy-bank-meta"
version = "0.0.0"
edition = "2021"
publish = false
authors = ["Etienne Wallet"]
[dependencies.piggy-bank]
path = ".."

[dependencies.multiversx-sc-meta-lib]
version = "0.64.1"
